meta-openembedded: fetchmail: update SRC_URI
ERROR: fetchmail-6.3.26-r0 do_checkuri: Fetcher failure for URL: 'http://download.berlios.de/fetchmail/fetchmail-6.3.26.tar.xz'. URL http://download.berlios.de/fetchmail/fetchmail-6.3.26.tar.xz doesn't work
ERROR: fetchmail-6.3.26-r0 do_checkuri: Function failed: do_checkuri
ERROR: Logfile of failure stored in: /home/akuster/oss/maint/poky/build/tmp/work/i586-poky-linux/fetchmail/6.3.26-r0/temp/log.do_checkuri.28438
ERROR: Task (/home/akuster/oss/maint/meta-openembedded/meta-networking/recipes-support/fetchmail/fetchmail_6.3.26.bb:do_checkuri) failed with exit code '1'

per homepage:
NEWS: NOW HOSTED BY SOURCEFORGE.NET AFTER BERLIOS SHUTDOWN

The BerliOS developer's website has shut down in the week following 2014 May 12th, and most of the fetchmail contents have been moved to SourceForge.net, including mailing list subscriptions, archives back to 2004, web site contents, download and Git repository. See http://sourceforge.net/projects/fetchmail/.

(From meta-openembedded rev: 3e294a32175b225f0d04fdaa106c7e92bcad7958)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>